### ISSUE TITLE
phaserotate on BlockVisibilities?

### ISSUE THREAD

**Issue by hrampadarath** [SKA-ScienceDataProcessor/algorithm-reference-library#3]
Hi Tim,

I am attempting to phaserotate on a BlockVisibility, but the code phaserotate_visibility in operations.py only works for the type 'Visibility'. Is there a way to do the phase rotation for the type 'BlockVisibility'

Regards,
Hayden

**Comment by hrampadarath** [comment]
Solved it by converting the BlockVisibility to Visibility using convert_blockvisibility_to_visibility in coalesce.py

**Comment by timcornwell** [comment]
That will work for now. I’ll put in a phase rotate for BlockVisibility

Cheers,
Tim

On 17 July 2017 at 5:18:34 pm, Hayden Rampadarath (notifications@github.com)
wrote:

Solved it by converting the BlockVisibility to Visibility using
convert_blockvisibility_to_visibility in coalesce.py

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SKA-ScienceDataProcessor/algorithm-reference-library/issues/3#issuecomment-315794651>,
or mute the thread
