### ISSUE TITLE
Read MS file error?

### ISSUE THREAD

**Issue by cnwangfeng** [SKA-ScienceDataProcessor/algorithm-reference-library#43]
Hi Tim, 

I want to open MS file by function create_batchvisitility_from _ms. The MS file was gotten from EoR Blind challenge which is about 474MB. My computer has 32GB memory. However, the ARL reports out of memory: 

*** mach_vm_map(size=18446744066256998400) failed (error code=3)
python(57221,0x11d8545c0) malloc: *** set a breakpoint in malloc_error_break to debug
Terminated: 15

I tracked the codes and error would occur at Line 835 of memory_data_models.py. 

            desc = [('index', '>i8'),
                    ('uvw', '>f8', (nants, nants, 3)),
                    ('time', '>f8'),
                    ('integration_time', '>f8'),
                    ('vis', '>c16', (nants, nants, nchan, npol)),
                    ('weight', '>f8', (nants, nants, nchan, npol)),
                    ('imaging_weight', '>f8', (nants, nants, nchan, npol))]
            data = numpy.zeros(shape=[ntimes], dtype=desc)

nants =4704, nchan =1 , npol = 4, ntimes = 8

Or it's not a bug which means I should find a big memory server to run it. 

Feng Wang

**Comment by timcornwell** [comment]
Hi,

Can you give me access to the data? It’s asking to allocate 16 Exabytes of memory!

Regards,
Tim

**Comment by cnwangfeng** [comment]
Hi,

https://www.dropbox.com/sh/7nful5ib7boyyhg/AACgo6fp3RJgBC7qQWzxrooOa?dl=0&lst=

I am using : eor_p_noise_p_fg_t_obsv_1000.0_hr.ms

407,086,215 bytes (407.3 MB on disk) for 89 items

Feng

**Comment by bnikolic** [comment]
Maybe a negative number has crept in somewhere so it is allocating two's
complement of the right size?

**Comment by timcornwell** [comment]
It seems that there is a limitation of structured arrays that:

ValueError: invalid shape in fixed-type tuple: dtype size in bytes must fit into a C int.

The vis, weight and imaging weight together overflow this. Removing two of these is ok. So it’s very close to the limit. 

Not obvious what to do. I’ll have to ponder this. The problem has not been visible so far because the maximum number of antennas used has been probably 512. 

However, clearly the following will also overflow if nchan is big enough.

('vis', '>c16', (nants, nants, nchan, npol)),

**Comment by fdulwich** [comment]
Hi Feng, Tim,

Thanks for sharing the link to the MS file. I had a look since I was curious, and I noticed that it's actually a concatenation of 21 single-channel OSKAR simulations, each with 224 stations. Unfortunately the CASA concat task that was used to generate it also duplicates rows in the ANTENNA table to make it very much longer, so it makes it look like there are (224 * 21 =) 4704 antennas, which is not the intention here. I guess it's not possible to assume that the number of rows in the ANTENNA table is the same as the actual number of antennas. Would it be possible to find the number of unique antenna positions to get this instead, or maybe if it's easier, use the total number of rows in the ANTENNA table divided by the total number of rows in the DATA_DESCRIPTION table? Someone with a better knowledge of what's allowed in the Measurement Set could say whether that's a good idea or not - I'm sure Tim would know.

(Incidentally, this also explains why you ran out of memory, as the ARL data structure would need almost 50 GB if it really was with 4704 antennas!)

Cheers,
Fred

**Comment by cnwangfeng** [comment]
Hi all, 

I have further tracked the codes and I agreed with Fred that the wrong values of ANTENNA number would the reason for the error. 

Feng

**Comment by cnwangfeng** [comment]
I suppose to close this issue because I think there are some obvious mistakes in that specified MS file. It is not worth to modify ARL codes to read the data from a wrong MS file.  
1. Two fields, i.e., anntena1 and anntenna2, written in the main data,  are greater than the number of antennas. 
2. Wrong data concatenation.
