### ISSUE TITLE
Help for the imaging-2d

### ISSUE THREAD

**Issue by cnwangfeng** [SKA-ScienceDataProcessor/algorithm-reference-library#44]
Hi all, 

I am trying to write a program using ARL to get a dirty image.  However I got the errors as follows. Or I have some confusions on how to invoke a proper function. 

Exception has occurred: ValueError
non-broadcastable output operand with shape (1,6,6) doesn't match the broadcast shape (4,6,6)
File "/Users/wangfeng/dev/algorithm-reference-library/processing_components/griddata/gridding.py", line 117, in grid_visibility_to_griddata cf.data[chan, :, zzc, vvf, uuf, :, :] * v[:, numpy.newaxis, numpy.newaxis] File "/Users/wangfeng/dev/algorithm-reference-library/processing_components/imaging/base.py", line 172, in invert_2d griddata, sumwt = grid_visibility_to_griddata(svis, griddata=griddata, cf=cf) File "/Users/wangfeng/Dev/test/arl-1/msImager.py", line 69, in <module> dirty, sumwt = invert_2d(vt, model, context='2d’)

I have read the manual and arl documents for many times. So, I am very sorry to trouble you. 

""" Unit tests for visibility operations

"""
import sys
import unittest
import logging
import logging.config

from data_models.parameters import arl_path

from processing_components.visibility.base import create_blockvisibility_from_ms, create_visibility_from_ms
from processing_components.visibility.operations import integrate_visibility_by_channel

#logging.config.fileConfig("~/dev/test/arl-1/arl.log")
log = logging.getLogger(__name__)

log.setLevel(logging.DEBUG)
log.addHandler(logging.StreamHandler(sys.stdout))
log.addHandler(logging.StreamHandler(sys.stderr))

from wrappers.serial.visibility.base import create_visibility
from wrappers.serial.skycomponent.operations import create_skycomponent
from wrappers.serial.image.operations import show_image, export_image_to_fits
from wrappers.serial.image.deconvolution import deconvolve_cube, restore_cube
from wrappers.serial.visibility.iterators import vis_timeslice_iter
from wrappers.serial.simulation.testing_support import create_named_configuration, create_test_image
from wrappers.serial.imaging.base import create_image_from_visibility
from workflows.serial.imaging.imaging_serial import invert_list_serial_workflow, predict_list_serial_workflow

from data_models.polarisation import PolarisationFrame

from processing_library.image.operations import copy_image, create_empty_image_like
from processing_components.image.operations import import_image_from_fits
from processing_components.imaging.base import predict_2d, invert_2d, create_image_from_visibility
from processing_components.image.deconvolution import deconvolve_cube, restore_cube
from processing_components.simulation.testing_support import create_test_image, create_named_configuration
from wrappers.serial.image.operations import export_image_to_fits

from matplotlib import pyplot as plt

msfile = arl_path("data/vis/ASKAP_example.ms")

vtlist = create_blockvisibility_from_ms(msfile)
from processing_components.visibility.coalesce import convert_blockvisibility_to_visibility

vt = convert_blockvisibility_to_visibility(vtlist[0])
plt.clf() 
uvw = vt.data['uvw']
plt.plot(vt.data['uvw'][:,0], vt.data['uvw'][:,1], '.', color='b')
plt.plot(-vt.data['uvw'][:,0], -vt.data['uvw'][:,1], '.', color='b')
plt.show()
print (vt)

model = create_image_from_visibility(vt, npixel=1024)
dirty, sumwt = invert_2d(vt, model, context='2d')

show_image(dirty)

**Comment by timcornwell** [comment]
Hi,

It looks like the polarisation is mismatched. The visibility data probably has 4 values (e.g. XX, XY, YX, YY) and the image has just one polarisation.

Can you print the image and the visibility? That will give a summary of the two including polarisation information.

Tim

**Comment by cnwangfeng** [comment]
Dear Tim,

Yes. I also tracked the errors many times but can’t find the problem. I used a MS file delivered by ARL itself. It can be found under ARL directory.

msfile = arl_path("data/vis/ASKAP_example.ms”)


I can show UV correctly.
Feng

**Comment by timcornwell** [comment]
Hi,

There are a couple of problems:

The entire MS is loaded. A subset can be loaded by e.g.

vtlist = create_blockvisibility_from_ms(msfile, channum=numpy.arange(16))

The input data is linear polarisation (i.e. XX, XY, YX, YY), and the default image polarisation is I. This conversion is failing.

If I set the image polarisation to be stokesIQUV then I get an empty image even though the visibility data is not zero.

The latter two are bugs. I’ll try to fix these.

Regards,
Tim

**Comment by timcornwell** [comment]
Hi Feng,

I’ve made some changes in the ARL github. You will need to convert the visibility from linear to stokes I as below. If you want polarised images you should use convert_visibility_to_stokes instead of convert_visibility_to_stokesI. I’ve added a test (test_invert) in tests/processing_components/test_visibility_ms.py. Below I include a modified version of your script.

I presume you installed ARL using git. If so, do a git pull. If not, you should make an installation using git clone:

git clone https://github.com/SKA-ScienceDataProcessor/algorithm-reference-library.git

Regards,
Tim



import sys
import unittest
import logging
import numpy

from data_models.parameters import arl_path

from processing_components.visibility.base import create_blockvisibility_from_ms, create_visibility_from_ms
from processing_components.visibility.operations import integrate_visibility_by_channel

from wrappers.serial.visibility.base import create_visibility
from wrappers.serial.skycomponent.operations import create_skycomponent
from wrappers.serial.image.operations import show_image, export_image_to_fits
from wrappers.serial.image.deconvolution import deconvolve_cube, restore_cube
from wrappers.serial.visibility.iterators import vis_timeslice_iter
from wrappers.serial.simulation.testing_support import create_named_configuration, create_test_image
from wrappers.serial.imaging.base import create_image_from_visibility
from workflows.serial.imaging.imaging_serial import invert_list_serial_workflow, predict_list_serial_workflow

from data_models.polarisation import PolarisationFrame

from processing_library.image.operations import copy_image, create_empty_image_like
from processing_components.image.operations import import_image_from_fits
from processing_components.imaging.base import predict_2d, invert_2d, create_image_from_visibility
from processing_components.image.deconvolution import deconvolve_cube, restore_cube
from processing_components.simulation.testing_support import create_test_image, create_named_configuration
from wrappers.serial.image.operations import export_image_to_fits
from processing_components.visibility.operations import convert_visibility_to_stokesI
from processing_components.image.operations import qa_image

from matplotlib import pyplot as plt

log = logging.getLogger()

log.setLevel(logging.DEBUG)
log.addHandler(logging.StreamHandler(sys.stdout))
log.addHandler(logging.StreamHandler(sys.stderr))

msfile = arl_path("data/vis/ASKAP_example.ms")

vtlist = create_blockvisibility_from_ms(msfile, channum=numpy.arange(16))

print(vtlist[0])
print(numpy.max(numpy.abs(vtlist[0].vis)))

from processing_components.visibility.coalesce import convert_blockvisibility_to_visibility

vt = convert_blockvisibility_to_visibility(vtlist[0])
plt.clf()
uvw = vt.data['uvw']
plt.plot(vt.data['uvw'][:,0], vt.data['uvw'][:,1], '.', color='b')
plt.plot(-vt.data['uvw'][:,0], -vt.data['uvw'][:,1], '.', color='b')
plt.show()
print (vt)

plt.clf()
uvdist=numpy.hypot(vt.data['uvw'][:,0], vt.data['uvw'][:,1])
plt.plot(uvdist, numpy.abs(vt.vis), '.')
plt.show()

visI = convert_visibility_to_stokesI(vt)
model = create_image_from_visibility(vt, npixel=1024)
dirty, sumwt = invert_2d(visI, model, context='2d')

print(qa_image(dirty))

show_image(dirty)
plt.show()

**Comment by timcornwell** [comment]
Good news!

Yes, I can include the uvfits reader. You can send me the code or submit a pull request to github.

Cheers,
Tim

**Comment by cnwangfeng** [comment]
Thanks. I opened a pull request. 

Cheers, 

Feng
